#!/bin/bash
# Quick tool listing script

echo "GitHub Manager MCP Server - Available Tools"
echo "============================================"
echo ""
echo "📦 Repository Management (8 tools)"
echo "   list_repositories, get_repository_info, create_repository,"
echo "   update_repository, delete_repository, search_repositories,"
echo "   get_repository_topics, set_repository_topics"
echo ""
echo "🐛 Issues (3 tools)"
echo "   list_issues, create_issue, close_issue"
echo ""
echo "🔀 Pull Requests (3 tools)"
echo "   list_pull_requests, create_pull_request, merge_pull_request"
echo ""
echo "🎉 Releases (2 tools)"
echo "   list_releases, create_release"
echo ""
echo "🏷️  Labels (2 tools)"
echo "   list_labels, create_label"
echo ""
echo "⚙️  Workflows (1 tool)"
echo "   list_workflow_runs"
echo ""
echo "💼 Workspace (8 tools)"
echo "   list_workspace_repos, clone_repository, pull_repository,"
echo "   get_repository_status, sync_all_repositories, delete_workspace_repo,"
echo "   create_branch, switch_branch"
echo ""
echo "💾 Backup (4 tools)"
echo "   backup_repository, backup_all_repositories,"
echo "   list_backups, restore_repository"
echo ""
echo "============================================"
echo "Total: 31 tools"
echo ""
echo "📚 Resources:"
echo "   • config://github - View configuration"
echo "   • status://rate-limit - API rate limits"
echo "   • docs://tools - Full documentation"
echo ""
echo "For detailed info, see: README.md"
echo "For MCP client access: Use 'docs://tools' resource"
